server:
  port: 9002
spring:
  application:
    name: cosmost-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    include: aws, local-db
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://13.125.238.75:8761/eureka
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
jwt:
  tokenValidTime: 1800000
  secret: COS-MOST-TEAM-SECRET-KEY

