server:
  port: 9002
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    include: aws, local-db

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
jwt:
  tokenValidTime: 1800000
  secret: COS-MOST-TEAM-SECRET-KEY

